/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stundenplan.oberflaechen;

import javax.swing.JToggleButton;
import stundenplan.Klasse;
import stundenplan.datenbank.IConnection;
import stundenplan.datenbank.DatenbankFabrik;

/**
 * Die LehrerEditGUI Klasse
 * Es kann das Formular jeweils mit oder ohne ausgewähltem Lehrer aufgerufen werden.
 * @author fielesebastian
 */
public class KlasseEditGUI extends javax.swing.JFrame {
    
    // Datenbank verbinden
    private IConnection verbinde = null;
    private Klasse klasse;

    /**
     * Neue LehrerEditGUI laden
     */
    public KlasseEditGUI() {
        init();
        // Fensterüberschrift neu setzen
        lbl_klasse_ueberschrift.setText("Klasse anlegen");
    }
    
    /**
     * LehrerEditGUI mit dem ausgewähltem Lehrer laden
     * 
     * @param name
     */
    public KlasseEditGUI(String name) {
        init();
        
        // Datenbank nach dem ausgewählten Lehrer abfragen
        try {
            verbinde = DatenbankFabrik.getIConnection();
            klasse = verbinde.getSelectedKlasse(name);
            // Kürzel der Klasse auslesen
            String klasse_kuerzel = klasse.getKuerzel();

            txt_klasse_kuerzel.setText(klasse_kuerzel);
        } catch (Exception e) {
            System.out.println(e);
        } finally {
            if (verbinde != null) {
                verbinde.schliesseVerbindung();
            }
        }
    }
    
    private void init() {
        initComponents();
        // Zentriert das Fenster
        setLocationRelativeTo(this);
        // Fenster auf definierte Größe setzen
        //this.setSize(418, 350);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_klasse_ueberschrift = new javax.swing.JLabel();
        txt_klasse_kuerzel = new javax.swing.JTextField();
        lbl_klasse_edit_kuerzel = new javax.swing.JLabel();
        btn_klasse_abbrechen = new javax.swing.JButton();
        btn_klasse_speichern = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Klasse bearbeiten");

        lbl_klasse_ueberschrift.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_klasse_ueberschrift.setText("Klasse bearbeiten");

        txt_klasse_kuerzel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_klasse_kuerzel.setPreferredSize(new java.awt.Dimension(90, 30));

        lbl_klasse_edit_kuerzel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_klasse_edit_kuerzel.setText("Kürzel");

        btn_klasse_abbrechen.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btn_klasse_abbrechen.setText("Abbrechen");
        btn_klasse_abbrechen.setMaximumSize(new java.awt.Dimension(80, 30));
        btn_klasse_abbrechen.setMinimumSize(new java.awt.Dimension(80, 30));
        btn_klasse_abbrechen.setPreferredSize(new java.awt.Dimension(80, 30));
        btn_klasse_abbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_klasse_abbrechenActionPerformed(evt);
            }
        });

        btn_klasse_speichern.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_klasse_speichern.setText("Speichern");
        btn_klasse_speichern.setMaximumSize(new java.awt.Dimension(90, 30));
        btn_klasse_speichern.setMinimumSize(new java.awt.Dimension(90, 30));
        btn_klasse_speichern.setPreferredSize(new java.awt.Dimension(90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btn_klasse_abbrechen, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_klasse_speichern, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_klasse_edit_kuerzel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_klasse_kuerzel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbl_klasse_ueberschrift))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_klasse_ueberschrift)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_klasse_edit_kuerzel)
                    .addComponent(txt_klasse_kuerzel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_klasse_abbrechen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_klasse_speichern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_klasse_abbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_klasse_abbrechenActionPerformed
        // Fenster schliessen
        this.setVisible(false);
    }//GEN-LAST:event_btn_klasse_abbrechenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_klasse_abbrechen;
    private javax.swing.JButton btn_klasse_speichern;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_klasse_edit_kuerzel;
    private javax.swing.JLabel lbl_klasse_ueberschrift;
    private javax.swing.JTextField txt_klasse_kuerzel;
    // End of variables declaration//GEN-END:variables
}
