/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stundenplan;

/**
 *
 * @author rawsta
 */
public class LehrerEditGUI extends javax.swing.JFrame {
    
    // Datenbank verbinden
    private IConnection connect = null;

    /**
     * Creates new form LehrerEdit
     */
    public LehrerEditGUI() {
        initComponents();
        setLocationRelativeTo(this); // Zentriert das Fenster
    }
    
    
    public LehrerEditGUI(String auswahl) {
        
        Lehrer tempLehrer = null;
        
        try {
            connect = DatabaseFactory.getIConnection();
            tempLehrer = connect.getSelectedLehrer(auswahl);
        } catch (Exception e) {
            System.out.println(e);
        } finally {
            if (connect != null) {
                connect.closeConnection();
            }
        }
        initComponents();
        setLocationRelativeTo(this); // Zentriert das Fenster
        
        String l_name = tempLehrer.getName();
        String l_short = tempLehrer.getKuerzel();
                
        txt_teacher_name.setText(l_name);
        txt_teacher_short.setText(l_short);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_teacher_edit = new javax.swing.JLabel();
        lbl_teacher_edit_name = new javax.swing.JLabel();
        txt_teacher_name = new javax.swing.JTextField();
        txt_teacher_short = new javax.swing.JTextField();
        lbl_teacher_edit_short = new javax.swing.JLabel();
        btn_teacher_save = new javax.swing.JButton();
        btn_teacher_save1 = new javax.swing.JButton();

        lbl_teacher_edit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_teacher_edit.setText("Lehrer bearbeiten");

        lbl_teacher_edit_name.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_teacher_edit_name.setText("Name");

        txt_teacher_name.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_teacher_name.setPreferredSize(new java.awt.Dimension(90, 30));

        txt_teacher_short.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_teacher_short.setPreferredSize(new java.awt.Dimension(90, 30));

        lbl_teacher_edit_short.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_teacher_edit_short.setText("Kürzel");

        btn_teacher_save.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        btn_teacher_save.setText("Abbrechen");
        btn_teacher_save.setMaximumSize(new java.awt.Dimension(80, 30));
        btn_teacher_save.setMinimumSize(new java.awt.Dimension(80, 30));
        btn_teacher_save.setPreferredSize(new java.awt.Dimension(80, 30));

        btn_teacher_save1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_teacher_save1.setText("Speichern");
        btn_teacher_save1.setMaximumSize(new java.awt.Dimension(90, 30));
        btn_teacher_save1.setMinimumSize(new java.awt.Dimension(90, 30));
        btn_teacher_save1.setPreferredSize(new java.awt.Dimension(90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_teacher_edit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_teacher_save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_teacher_save1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_teacher_edit_name, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_teacher_edit_short, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_teacher_name, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txt_teacher_short, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_teacher_edit)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_teacher_edit_name)
                    .addComponent(txt_teacher_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_teacher_edit_short)
                    .addComponent(txt_teacher_short, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_teacher_save1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_teacher_save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_teacher_save;
    private javax.swing.JButton btn_teacher_save1;
    private javax.swing.JLabel lbl_teacher_edit;
    private javax.swing.JLabel lbl_teacher_edit_name;
    private javax.swing.JLabel lbl_teacher_edit_short;
    private javax.swing.JTextField txt_teacher_name;
    private javax.swing.JTextField txt_teacher_short;
    // End of variables declaration//GEN-END:variables
}
