/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stundenplan;

/**
 *
 * @author fielesebastian
 */
public class Uebersicht extends javax.swing.JFrame {

    /**
     * Creates new form Uebersicht
     */
    public Uebersicht() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_window_title = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();
        btn_class_new = new javax.swing.JButton();
        btn_teacher_new = new javax.swing.JButton();
        btn_splan_current = new javax.swing.JButton();
        btn_splan_new = new javax.swing.JButton();
        btn_splan_latest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_teacher = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_classes = new javax.swing.JList();
        btn_teacher_edit = new javax.swing.JButton();
        btn_teacher_splan = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btn_block_new = new javax.swing.JButton();
        btn_subject_new = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_window_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_window_title.setText("Stundenplanverwaltungsoberfläche");

        btn_close.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        btn_close.setText("Programm beenden");

        btn_class_new.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        btn_class_new.setText("Neue Klasse anlegen");
        btn_class_new.setMaximumSize(new java.awt.Dimension(180, 40));
        btn_class_new.setMinimumSize(new java.awt.Dimension(180, 40));
        btn_class_new.setPreferredSize(new java.awt.Dimension(180, 40));
        btn_class_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_class_newActionPerformed(evt);
            }
        });

        btn_teacher_new.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        btn_teacher_new.setText("Neue Lehrer anlegen");
        btn_teacher_new.setMaximumSize(new java.awt.Dimension(180, 40));
        btn_teacher_new.setMinimumSize(new java.awt.Dimension(180, 40));
        btn_teacher_new.setPreferredSize(new java.awt.Dimension(180, 40));

        btn_splan_current.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        btn_splan_current.setText("Aktuelle Stundenpläne ansehen");
        btn_splan_current.setMaximumSize(new java.awt.Dimension(200, 30));
        btn_splan_current.setMinimumSize(new java.awt.Dimension(200, 30));
        btn_splan_current.setPreferredSize(new java.awt.Dimension(220, 50));

        btn_splan_new.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        btn_splan_new.setText("Neuen Stundenplan anlegen");
        btn_splan_new.setMaximumSize(new java.awt.Dimension(200, 30));
        btn_splan_new.setMinimumSize(new java.awt.Dimension(200, 30));
        btn_splan_new.setPreferredSize(new java.awt.Dimension(220, 50));

        btn_splan_latest.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        btn_splan_latest.setText("vergangene Stundenpläne");
        btn_splan_latest.setMaximumSize(new java.awt.Dimension(200, 30));
        btn_splan_latest.setMinimumSize(new java.awt.Dimension(200, 30));
        btn_splan_latest.setPreferredSize(new java.awt.Dimension(220, 50));
        btn_splan_latest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_splan_latestActionPerformed(evt);
            }
        });

        lst_teacher.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Lehrer 1", "Lehrer 2", "Lehrer 3", "Lehrer 4", "Lehrer 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lst_teacher.setPreferredSize(new java.awt.Dimension(150, 50));
        jScrollPane1.setViewportView(lst_teacher);

        lst_classes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Klasse 1", "Klasse 2", "Klasse 3", "Klasse 4", "Klasse 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lst_classes);

        btn_teacher_edit.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        btn_teacher_edit.setText("Lehrer bearbeiten");
        btn_teacher_edit.setMaximumSize(new java.awt.Dimension(180, 40));
        btn_teacher_edit.setMinimumSize(new java.awt.Dimension(180, 40));
        btn_teacher_edit.setPreferredSize(new java.awt.Dimension(180, 40));

        btn_teacher_splan.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        btn_teacher_splan.setText("Stundenplan anzeigen");
        btn_teacher_splan.setMaximumSize(new java.awt.Dimension(180, 40));
        btn_teacher_splan.setMinimumSize(new java.awt.Dimension(180, 40));
        btn_teacher_splan.setPreferredSize(new java.awt.Dimension(180, 40));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton3.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jButton3.setText("Klasse bearbeiten");
        jButton3.setMaximumSize(new java.awt.Dimension(180, 40));
        jButton3.setMinimumSize(new java.awt.Dimension(180, 40));
        jButton3.setPreferredSize(new java.awt.Dimension(180, 40));

        jButton4.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jButton4.setText("Stundenplan anzeigen");
        jButton4.setMaximumSize(new java.awt.Dimension(180, 40));
        jButton4.setMinimumSize(new java.awt.Dimension(180, 40));
        jButton4.setPreferredSize(new java.awt.Dimension(180, 40));

        btn_block_new.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        btn_block_new.setText("Neuer Unterrichtsblock");
        btn_block_new.setMaximumSize(new java.awt.Dimension(200, 30));
        btn_block_new.setMinimumSize(new java.awt.Dimension(200, 30));
        btn_block_new.setPreferredSize(new java.awt.Dimension(220, 50));

        btn_subject_new.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        btn_subject_new.setText("Neues Fach");
        btn_subject_new.setMaximumSize(new java.awt.Dimension(200, 30));
        btn_subject_new.setMinimumSize(new java.awt.Dimension(200, 30));
        btn_subject_new.setPreferredSize(new java.awt.Dimension(220, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_block_new, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_subject_new, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_close))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_splan_current, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(btn_splan_new, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(btn_splan_latest, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_teacher_splan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_teacher_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_teacher_new, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, Short.MAX_VALUE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_class_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lbl_window_title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_window_title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_splan_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_splan_latest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_splan_current, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_teacher_splan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_teacher_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_teacher_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_class_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_close)
                    .addComponent(btn_block_new, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_subject_new, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_class_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_class_newActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_class_newActionPerformed

    private void btn_splan_latestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_splan_latestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_splan_latestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uebersicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uebersicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uebersicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uebersicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Uebersicht().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_block_new;
    private javax.swing.JButton btn_class_new;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_splan_current;
    private javax.swing.JButton btn_splan_latest;
    private javax.swing.JButton btn_splan_new;
    private javax.swing.JButton btn_subject_new;
    private javax.swing.JButton btn_teacher_edit;
    private javax.swing.JButton btn_teacher_new;
    private javax.swing.JButton btn_teacher_splan;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_window_title;
    private javax.swing.JList lst_classes;
    private javax.swing.JList lst_teacher;
    // End of variables declaration//GEN-END:variables
}
